### ISSUE TITLE
missing something!

### ISSUE THREAD

**Issue by matingholami** [poormonfared/sb-admin2#2]
in your RTL version, icons & graphs are disappeared! and collapse tags do not work :|

**Comment by ahmadbehjati** [comment]
سلام حاج میثم
آیکون ها و خیلی از فایل های جاوا اسکریپت رو جا انداختی که باو
I Love You
بوس بوس

**Comment by mtaraabi** [comment]
The issue with icons happen as result of missing folder and wrong file reference in all of the project files.

Here is a quick fix for icons issue 

1- Download the english version form this link https://startbootstrap.com/template-overviews/sb-admin-2/

3- open the download folder then copy vendor folder and then paste in the RLT folder 

2- in each page you need to correct the path of Awesome Font. In another word, just replace  
the following code. 

`<link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">`

By this code 

`
        <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">`

Then all the icons will appear.

All thanks for Meysam  and his effort in this RLT version

Cheers
Mohammad

**Comment by poormonfared** [comment]
thanks for your help
